### PR TITLE
Bug/manufacturer check

### LINKED ISSUE #270: Yesoul S3 is not recognized by build 94 and later
Sebastian's Pixel 6 has build 93, that does not have specific Yesoul S3 entry in the device map. Whereas his Xiami Mi A2 has Build 98 which has that entry (#259). The entry was added so the bike is recognized not as a Generic FTMS bike, but as Yesoul.

Sebastian debugged the issue and the root cause is case sensitivity for the manufacturer check: https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/blob/daa21215661750569b506faae4b0a4eab4c48a4e/lib/devices/gadgets/fitness_equipment.dart#L449
```
    return manufacturerName!.contains(descriptor!.manufacturerPrefix) ||
        descriptor!.manufacturerPrefix == "Unknown";
```

The actual manufacturer string coming from the device is `"FUJISAN YESOUL"` whereas the device map entry in the code is `"Yesoul"`.

### PR DESCRIPTION
**Pull request by sebastiankutschbach**
Fixes #270, only the first 2 commits are directly related to the bug. The other commits were side products. One was triggered by the regeneration of the build_runner output. The others were otuput of the formatter.
If I configured something wrong, please just cherry pick the relevant commits...

With the unit test for fitness_equipment.dart we have the foundation to add more tests to at least the discover method. If you like the way of testing, I can add more tests later...

### CODE REVIEW

File: lib/devices/gadgets/fitness_equipment.dart [hunk 1]
```diff
@@ -392,62 +393,65 @@ class FitnessEquipment extends DeviceBase {
...
+    if (_logLevel >= logLevelInfo) {
+      Logging.log(
+        _logLevel,
+        logLevelInfo,
+        "FITNESS_EQUIPMENT",
+        "_checkManufacturerName",
+        "ensuring that manufacturer name ($manufacturerName) contains manufacturer prefix ${descriptor!.manufacturerPrefix}",
+      );
+    }
+    return manufacturerName!.toLowerCase().contains(descriptor!.manufacturerPrefix.toLowerCase()) ||
```
Comment (MrCsabaToth) [inline lib/devices/gadgets/fitness_equipment.dart:416]: Can we make this robust against `manufacturerName` being `null`? In that case we'd return false.

File: analysis_options.yaml [hunk 2]
```diff
@@ -4,3 +4,7 @@ include: package:flutter_lints/flutter.yaml
 # https://dart.dev/guides/language/analysis-options
 linter:
   rules:
+
+analyzer:
+  exclude:
+    - test/**.mocks.dart
```
Comment (MrCsabaToth) [inline analysis_options.yaml:10]: What was analysis's problem with the mock file? I already have some, but haven't had a failure yet.

**Review by MrCsabaToth — CHANGES_REQUESTED** [review]
Thank you so much for your work Sebastian!

File: analysis_options.yaml (hunk 2 above)
Comment (MrCsabaToth) [reply analysis_options.yaml:10]: Oh, I see in the Action log `The '?' is unnecessary because 'Null' is nullable without it • test/fitness_equipment_test.mocks.dart:153:18 • unnecessary_question_mark`. Oh well. We can exclude the mocks!

File: lib/devices/gadgets/fitness_equipment.dart (hunk 1 above)
Comment (sebastiankutschbach) [reply lib/devices/gadgets/fitness_equipment.dart]: Done.

File: lib/devices/gadgets/fitness_equipment.dart [hunk 3]
```diff
@@ -413,8 +413,8 @@ class FitnessEquipment extends DeviceBase {
         "ensuring that manufacturer name ($manufacturerName) contains manufacturer prefix ${descriptor!.manufacturerPrefix}",
       );
     }
-    return manufacturerName!.toLowerCase().contains(descriptor!.manufacturerPrefix.toLowerCase()) ||
-        descriptor!.manufacturerPrefix == "Unknown";
+    return manufacturerName?.toLowerCase().contains(descriptor!.manufacturerPrefix.toLowerCase()) ??
+        false || descriptor!.manufacturerPrefix == "Unknown";
```
Comment (MrCsabaToth) [inline lib/devices/gadgets/fitness_equipment.dart:417]: Due to operator precedence (https://support.wahoofitness.com/hc/en-us/articles/204280494-Android-Bluetooth-Troubleshooting) I think (not 100% sure, but kind of confident) we want a parentheses around `(manufacturerName?.toLowerCase().contains(descriptor!.manufacturerPrefix.toLowerCase()) ?? false)` otherwise the `??` is evaluated after the `||` so the way it is now it'll be `(false || descriptor!.manufacturerPrefix == "Unknown")`. (BTW to not be hypocritical: after I merge your PR I'll also make the `descriptor!` part robust, but I don't want to drag this PR out with that.)

**Review by MrCsabaToth — CHANGES_REQUESTED** [review]
We are almost there. I have some insights about operator precedence, we may need a parentheses.

File: lib/devices/gadgets/fitness_equipment.dart [hunk 4]
```diff
@@ -413,8 +413,11 @@ class FitnessEquipment extends DeviceBase {
         "ensuring that manufacturer name ($manufacturerName) contains manufacturer prefix ${descriptor!.manufacturerPrefix}",
       );
     }
-    return manufacturerName?.toLowerCase().contains(descriptor!.manufacturerPrefix.toLowerCase()) ??
-        false || descriptor!.manufacturerPrefix == "Unknown";
+    if (manufacturerName == null) {
```
Comment (MrCsabaToth) [inline lib/devices/gadgets/fitness_equipment.dart:416]: I like the breakdown. However it's not 100% equivalent to the previous version. If `descriptor!.manufacturerPrefix == "Unknown"` but `manufacturerName` is null. I guess that can happen when even a 2nd read is not successful. I had some problems in the past, that's why I have the 2nd try for read. I can see two ways: 1. Return true immediately if `descriptor!.manufacturerPrefix == "Unknown"`, and then have the other predicate, in that case the `??` can remain. The other way is maybe to use a magic value other than the null for the initial value of `manufacturerName`. `null` indicates that the the reading wasn't attempted yet, and once it failed there wouldn't be consecutive attempts. Maybe we can just have it as a non nullable variable with an empty string initial value. If we assume that no machine will report empty string value (I think we can assume that) we can just get rid of the whole nullability. I'm not sure if that'll affect other files of the app. Now that I dig deeper this whole clause was like that even before your change (both with exclamation marks), so we can also decide to defer further changes after your PR (although that's somewhat dangerous because maybe I'll forget it).

**Review by MrCsabaToth — CHANGES_REQUESTED** [review]
Sorry for dragging this out even longer

**Review by MrCsabaToth — APPROVED** [review]
